version: '2'

services:

  consul:
    image: consul:0.8.3
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    links:
      - myapp1
      - myapp2
    networks:
      - sky-net

  myapp1:
    image: myapp1
    build:
      context: ./app1
    environment:
      - PORT=10011
    ports:
      - "10011:10011"
    networks:
      - sky-net

  myapp2:
    image: myapp2
    build:
      context: ./app2
    environment:
      - PORT=10012
    ports:
      - "10012:10012"
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge