version: "3.3"

networks:
  traefik-net:
    external: true
    
services:

    app3:
      image: myapp3
      networks:
        - traefik-net
      deploy:
        labels:
          - "traefik.port=10000"
          - "traefik.docker.network=traefik-net"
          - "traefik.backend=myapp3"
          - "traefik.frontend.rule=Host:app3.traefik"

    app1:
      image: myapp1
      networks:
        - traefik-net
      deploy:
        labels:
          - "traefik.port=10011"
          - "traefik.docker.network=traefik-net"
          - "traefik.backend=myapp1"
          - "traefik.frontend.rule=Host:app1.traefik"

    app2:
      image: myapp2
      networks:
        - traefik-net
      deploy:
        labels:
          - "traefik.port=10012"
          - "traefik.docker.network=traefik-net"
          - "traefik.backend=myapp2"
          - "traefik.frontend.rule=Host:app2.traefik"

    traefik:
      image: traefik
      command: -c /dev/null --web --docker --docker.swarmmode --docker.watch --docker.domain=traefik --logLevel=DEBUG
      networks:
        - traefik-net
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      deploy:
        placement:
          constraints: [node.role == manager]
